### ISSUE TITLE
Pip installation incorrect

### ISSUE THREAD

**Issue by rverchere** [nuxeo/nuxeo-python-client#1]
Hello,

Using `pip`, the package name is incorrect. It should be the following instead of `nuxeo-client`:
```
pip install nuxeo-python-client
```

Moreover, when trying to import the new package, it fails, as it needs `poster` to be installed.
 ```
$ python
Python 2.7.13 (default, Dec 17 2016, 23:03:43)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from nuxeo import Nuxeo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nuxeo.py", line 10, in <module>
    from poster.streaminghttp import get_handlers
ImportError: No module named poster.streaminghttp
```

Installing `poster` resolve the issue :
```
$ pip install poster
Collecting poster
  Downloading poster-0.8.1.tar.gz
Building wheels for collected packages: poster
  Running setup.py bdist_wheel for poster ... done
  Stored in directory: /Users/rverchere/Library/Caches/pip/wheels/7f/50/85/e015e7056e73b6dac4653f1d27cee339c5adfa1b34c47bab9a
Successfully built poster
Installing collected packages: poster
Successfully installed poster-0.8.1
$ python
Python 2.7.13 (default, Dec 17 2016, 23:03:43)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from nuxeo import Nuxeo
>>> 
```

**Comment by BoboTiG** [comment]
Hello,

Thank you for the report, we planned to fix this, we will do it soon :)

**Comment by rverchere** [comment]
Hello,

you can also correct nuxeo import as written in the blog post  [here](https://www.nuxeo.com/blog/nuxeo-python-client-a-python-client-library-for-nuxeo-automation-and-rest-api/) ;)

`from nuxeo import Nuxeo` --> `from nuxeo.nuxeo import Nuxeo`

**Comment by BoboTiG** [comment]
Yep, it is on the todo list too :)
