### ISSUE TITLE
Reassign task give _read error

### ISSUE THREAD

**Issue by rverchere** [nuxeo/nuxeo-python-client#2]
Using the following code to reassign task works, but gives a python `_read` error.

- Code:
``` python
mydoc = nuxeo.repository().fetch("<doc-id>")
wf = mydoc.fetch_workflows()
for w in wf:
    tasks = w.fetch_tasks()
    for t in tasks:
        result = t.reassign("myself")
```
- Traceback:
```
Traceback (most recent call last):
  File "tasks.py", line 23, in <module>
    result = t.reassign("myself")
  File "/usr/local/lib/python2.7/site-packages/nuxeo/workflow.py", line 82, in reassign
    self._read(self._service._service.request('task/' + self.get_id() + '/reassign', query_params=query_params, method="PUT"))
  File "/usr/local/lib/python2.7/site-packages/nuxeo/workflow.py", line 98, in _read
    self.directive = obj['directive']
TypeError: string indices must be integers, not str
```
- Working tcp dump ;)
```
PUT //nuxeo/api/v1/task/<task-id>/reassign?actors=myself HTTP/1.1
Accept-Encoding: identity
Content-Length: 0
Connection: close
Accept: application/json+nxentity, */*
User-Agent: Python-urllib/2.7
Host: 127.0.0.1:8080
Cache-Control: no-cache
Content-Type: application/json
Authorization: Basic QWRtaW5pc3RyYXRvcjpBZG1pbmlzdHJhdG9y

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
X-UA-Compatible: IE=10; IE=11
Cache-Control: no-cache
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Length: 0
Date: Wed, 08 Mar 2017 14:04:44 GMT
Connection: close
```

I'm using LTS2015 nuxeo server for my tests.

**Comment by BoboTiG** [comment]
Thank you for the report, we will take a look soon.

**Comment by BoboTiG** [comment]
I am closing that issue as we rewrote the client and the function does not exist anymore.
