### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by alsilva86** [nuxeo/nuxeo-python-client#56]
Sorry to bother, now I trying to upload a blob I am receiving that error:

```python
 File "nuxeo-python-client/nuxeo/compat.py", line 58, in get_text
    data = data.decode('utf-8')
```

I did put a print to show data content on compat.py, it was "None":
```python
<Blob chunkCount=0, fileIdx='0', mimetype=None, name=None, size=0, uploadType='normal', uploaded='true', uploadedChunkIds=[], uploadedSize='61'>
None
```

This is my code: The test.txt exists and its still on same directory, here's the code snippet now:

```python
import configparser
from nuxeo.models import Document, FileBlob
from nuxeo.exceptions import UploadError
from nuxeo.client import Nuxeo
from flask import Flask, Blueprint, jsonify

appConfig = configparser.ConfigParser()
appConfig.read("../config/docsMS.ini")
nuxeoConfig = appConfig['Ambiente_ECM']

def insertFileTrunk(produto):
    new_file = Document(
    name='test.txt',
    type='File',
    properties={
        'dc:title': 'test',
    })
    # Connection
    host = nuxeoConfig['host']
    auth = (nuxeoConfig['user'], nuxeoConfig['password'])
    nuxeo = Nuxeo(host=host, auth=auth)
    batch = nuxeo.uploads.batch()
    file = nuxeo.documents.create(new_file, parent_path='/')
    print("Testando")
    # Upload a document
    blob = FileBlob('/home/andreluiz/dev/captalys/docsMS/docsMS/test.txt')
    try:
        uploaded = batch.upload(blob, chunked=False)
        print(uploaded)
    except UploadError:
        print("Erro")
    operation = nuxeo.operations.new('Blob.AttachOnDocument')
    operation.params = {'document': '/foo'}
    operation.input_obj = uploaded
    try:
        operation.execute()
    except UploadError:
            print("Erro")
    #return jsonify({"status": True})
if __name__ == '__main__':
    exit(main())
```

**Comment by BoboTiG** [comment]
What is the full exception?

**Comment by alsilva86** [comment]
127.0.0.1 - - [16/Apr/2018 13:39:37] "GET /docsTrunk/321321/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andreluiz/dev/captalys/docsMS/docsMS/trunk/view.py", line 8, in insertTrunk
    insertFileTrunk(produto)
  File "/home/andreluiz/dev/captalys/docsMS/docsMS/trunk/model.py", line 36, in insertFileTrunk
    operation.execute()
  File "/home/andreluiz/dev/captalys/nuxeo-python-client/nuxeo/models.py", line 611, in execute
    return self.service.execute(self, **kwargs)
  File "/home/andreluiz/dev/captalys/nuxeo-python-client/nuxeo/operations.py", line 191, in execute
    'POST', url, data=data, headers=headers, default=default)
  File "/home/andreluiz/dev/captalys/nuxeo-python-client/nuxeo/client.py", line 173, in request
    raise self._handle_error(exc)
  File "/home/andreluiz/dev/captalys/nuxeo-python-client/nuxeo/client.py", line 251, in _handle_error
    logger.exception('Remote exception: {}'.format(error))
  File "/home/andreluiz/dev/captalys/nuxeo-python-client/nuxeo/exceptions.py", line 57, in __str__
    return '{} error: {}'.format(self.status, get_text(self.message))
  File "/home/andreluiz/dev/captalys/nuxeo-python-client/nuxeo/compat.py", line 58, in get_text
    data = data.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by BoboTiG** [comment]
Could you enable logging and copy/paste what is printed?
```python
# Put those lines at the top of your script
from logging import basicConfig
log = basicConfig(level='DEBUG')
```

**Comment by alsilva86** [comment]
^T * Detected change in '/home/andreluiz/dev/captalys/docsMS/docsMS/trunk/model.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 192-267-153
DEBUG:nuxeo.client:Calling 'http://docs.captalyx.com.br:8080/nuxeo/api/v1/upload' with headers={'X-NXRepository': 'default', 'Content-Type': 'application/json', 'Accept': 'application/json+nxentity, */*', 'X-Application-Name': 'Python client', 'X-NXDocumentProperties': '*', 'X-Client-Version': '2.0.0'}, params={} and cookies=<RequestsCookieJar[]>
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): docs.captalyx.com.br
DEBUG:urllib3.connectionpool:http://docs.captalyx.com.br:8080 "POST /nuxeo/api/v1/upload HTTP/1.1" 201 58
DEBUG:nuxeo.client:Response from 'http://docs.captalyx.com.br:8080/nuxeo/api/v1/upload': '{"batchId":"batchId-cfa97139-4758-40c1-8a27-12ae0e9f0841"}' with cookies <RequestsCookieJar[]>
DEBUG:nuxeo.client:Calling 'http://docs.captalyx.com.br:8080/nuxeo/api/v1/repo/default/path/' with headers={'X-NXRepository': 'default', 'Content-Type': 'application/json', 'Accept': 'application/json+nxentity, */*', 'X-Application-Name': 'Python client', 'X-NXDocumentProperties': '*', 'X-Client-Version': '2.0.0'}, params={} and cookies=<RequestsCookieJar[]>
DEBUG:urllib3.connectionpool:http://docs.captalyx.com.br:8080 "POST /nuxeo/api/v1/repo/default/path/ HTTP/1.1" 201 None
DEBUG:nuxeo.client:Response from 'http://docs.captalyx.com.br:8080/nuxeo/api/v1/repo/default/path/': '{"entity-type":"document","repository":"default","uid":"888d1e7d-ad16-4f4b-957f-6249f552534f","path":"/test","type":"File","state":"project","parentRef":"8918995d-4f85-498a-a681-646aaa1ef889","isCheckedOut":true,"isVersion":false,"isProxy":false,"changeToken":"1523898767946","title":"test","lastModified":"2018-04-16T17:12:47.946Z","properties":{"uid:uid":null,"uid:major_version":0,"uid:minor_version":0,"file:content":null,"common:icon-expanded":null,"common:icon":"/icons/file.gif","files:files":[],"dc:description":null,"dc:language":null,"dc:coverage":null,"dc:valid":null,"dc:creator":"Administrator","dc:modified":"2018-04-16T17:12:47.946Z","dc:lastContributor":"Administrator","dc:rights":null,"dc:expired":null,"dc:format":null,"dc:created":"2018-04-16T17:12:47.946Z","dc:title":"test","dc:issued":null,"dc:nature":null,"dc:subjects":[],"dc:contributors":["Administrator"],"dc:source":null,"dc:publisher":null,"relatedtext:relatedtextresources":[]},"facets":["Versionable","Publishable","Commentable","HasRelatedText","Downloadable"]}' with cookies <RequestsCookieJar[]>
Testando
DEBUG:nuxeo.client:Calling 'http://docs.captalyx.com.br:8080/nuxeo/api/v1/upload/batchId-cfa97139-4758-40c1-8a27-12ae0e9f0841/0' with headers={'X-File-Size': '47', 'Content-Length': '47', 'X-NXRepository': 'default', 'X-Application-Name': 'Python client', 'Cache-Control': 'no-cache', 'X-File-Type': 'application/octet-stream', 'X-NXDocumentProperties': '*', 'Accept': 'application/json+nxentity, */*', 'Content-Type': 'application/json', 'X-File-Name': 'test', 'X-Client-Version': '2.0.0'}, params={} and cookies=<RequestsCookieJar[]>
DEBUG:urllib3.connectionpool:http://docs.captalyx.com.br:8080 "POST /nuxeo/api/v1/upload/batchId-cfa97139-4758-40c1-8a27-12ae0e9f0841/0 HTTP/1.1" 201 132
DEBUG:nuxeo.client:Response from 'http://docs.captalyx.com.br:8080/nuxeo/api/v1/upload/batchId-cfa97139-4758-40c1-8a27-12ae0e9f0841/0': '{"uploaded":"true","fileIdx":"0","uploadedSize":"47","uploadType":"normal","batchId":"batchId-cfa97139-4758-40c1-8a27-12ae0e9f0841"}' with cookies <RequestsCookieJar[]>
<Blob chunkCount=0, fileIdx='0', mimetype=None, name=None, size=0, uploadType='normal', uploaded='true', uploadedChunkIds=[], uploadedSize='47'>
DEBUG:nuxeo.client:Calling 'http://docs.captalyx.com.br:8080/nuxeo/api/v1/upload/batchId-cfa97139-4758-40c1-8a27-12ae0e9f0841/0/execute/Blob.AttachOnDocument' with headers={'X-NXRepository': 'default', 'X-NXDocumentProperties': '*', 'X-NXproperties': '*', 'X-Application-Name': 'Python client', 'Content-Type': 'application/json', 'X-Client-Version': '2.0.0', 'Accept': 'application/json+nxentity, */*'}, params={} and cookies=<RequestsCookieJar[]>
DEBUG:urllib3.connectionpool:http://docs.captalyx.com.br:8080 "POST /nuxeo/api/v1/upload/batchId-cfa97139-4758-40c1-8a27-12ae0e9f0841/0/execute/Blob.AttachOnDocument HTTP/1.1" 500 113
None
127.0.0.1 - - [16/Apr/2018 14:12:47] "GET /docsTrunk/321321/ HTTP/1.1" 500 -
INFO:werkzeug:127.0.0.1 - - [16/Apr/2018 14:12:47] "GET /docsTrunk/321321/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andreluiz/dev/captalys/docsMS/docsMS/trunk/view.py", line 8, in insertTrunk
    insertFileTrunk(produto)
  File "/home/andreluiz/dev/captalys/docsMS/docsMS/trunk/model.py", line 39, in insertFileTrunk
    operation.execute()
  File "/home/andreluiz/dev/captalys/nuxeo-python-client/nuxeo/models.py", line 611, in execute
    return self.service.execute(self, **kwargs)
  File "/home/andreluiz/dev/captalys/nuxeo-python-client/nuxeo/operations.py", line 191, in execute
    'POST', url, data=data, headers=headers, default=default)
  File "/home/andreluiz/dev/captalys/nuxeo-python-client/nuxeo/client.py", line 173, in request
    raise self._handle_error(exc)
  File "/home/andreluiz/dev/captalys/nuxeo-python-client/nuxeo/client.py", line 251, in _handle_error
    logger.exception('Remote exception: {}'.format(error))
  File "/home/andreluiz/dev/captalys/nuxeo-python-client/nuxeo/exceptions.py", line 57, in __str__
    return '{} error: {}'.format(self.status, get_text(self.message))
  File "/home/andreluiz/dev/captalys/nuxeo-python-client/nuxeo/compat.py", line 58, in get_text
    data = data.decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by alsilva86** [comment]
2018-04-16 15:58:27,054 ERROR [http-bio-0.0.0.0-8080-exec-44] [org.nuxeo.ecm.restapi.server.jaxrs.BatchUploadObject] Error while executing automation batch
org.nuxeo.ecm.core.api.NuxeoException: org.nuxeo.ecm.automation.TypeAdaptException: org.nuxeo.ecm.core.api.DocumentNotFoundException: /foo
  

Can you please advise if I can omit this parameter? Thats what I get from the server.

**Comment by alsilva86** [comment]
file = nuxeo.documents.create(new_file, parent_path='/default-domain/workspaces/Tests.1523561991886')
    print("Testando")
    # Upload a document
    blob = FileBlob('/home/andreluiz/dev/captalys/docsMS/docsMS/test')
    try:
        uploaded = batch.upload(blob, chunked=False)
        print(uploaded)
    except UploadError:
        print("Erro")
    operation = nuxeo.operations.new('Blob.AttachOnDocument')
    operation.params = {'document': '/default-domain/workspaces/Tests.1523561991886/foo'}
    operation.input_obj = uploaded
    try:	


It works fine now! A suggestion: for beginners at platform / nuxeo concepts, you guys should do a better path on the "/foo" parameter. Or work on the error replies.

Thanks for the support.

**Comment by BoboTiG** [comment]
We are currently working a new documentation that will be easier to follow and without "foo" paths :)
